apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: custom-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: custom-rolebinding
subjects:
- kind: ServiceAccount
  name: test
roleRef:
  kind: Role
  name: custom-role
  apiGroup: rbac.authorization.k8s.io