name: Build and Push Image

on:
  push:
    branches: [ "week-1" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: simple-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: {{ secret.DOCKER_HUB_USER }}
          password: {{ secret.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: {{ secret.DOCKER_HUB_USER }}/simple-app:${GITHUB_SHA}